### PR TITLE
Fix to allow the zkApp-cli to be used from a projects local node_modules

### LINKED ISSUE #485: Bug: zkapp-CLI breaks when used from local node_modules
If you don't install the CLI globally, but locally, i.e. `npm i zkapp-cli` (and call with `npx zk ...`), then the logic for getting the installed version fails:

```
zk deploy [alias]

Deploy or redeploy a zkApp

Options:
  -y, --yes      Respond `yes` to all confirmation prompts.
                 Allows running non-interactively within a script.     [boolean]
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]

TypeError: Cannot read properties of undefined (reading '0')
    at hasBreakingChanges (/home/sven/work/zk-hello-world/node_modules/zkapp-cli/src/lib/deploy.js:546:18)
    at deploy (/home/sven/work/zk-hello-world/node_modules/zkapp-cli/src/lib/deploy.js:49:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/home/sven/work/zk-hello-world/node_modules/zkapp-cli/src/bin/index.js:78:21)
```

Relevant code:
https://github.com/o1-labs/zkapp-cli/blob/75c14c9755eb2948ead21e22c31d62e510b39123/src/lib/deploy.js#L525
https://github.com/o1-labs/zkapp-cli/blob/75c14c9755eb2948ead21e22c31d62e510b39123/src/lib/deploy.js#L546

### PR DESCRIPTION
**Pull request by ymekuria**
Description 
Fixes #485 

**Problem** 

If a user doesn't install the CLI globally but does locally in a project with `npm i zkapp-cli`, the CLI fails when the user enters `zk deploy`. This occurs because the logic to check if a user needs to update their CLI version checks for a global installed package and fails if none is found. 

**Solution**

This PR first checks if a user has a local installed CLI pacakge and uses it to determine if they need to upgrade. If no local version is found, the users global package version is used to determine if they need to upgrade. 

**Tested**

This was tested manually by running `zk deploy` on a project with the CLI installed locally and not globally without errors.

### CODE REVIEW

File: src/lib/deploy.js [hunk 1]
```diff
@@ -523,13 +523,27 @@ async function getLatestCliVersion() {
 }
 
 async function getInstalledCliVersion() {
```
Comment (MartinMinkov) [inline src/lib/deploy.js:525]: Could we get rid of `async` if we don't await anything in this function?

File: src/lib/deploy.js [hunk 2]
```diff
@@ -539,14 +553,14 @@ When o1js and the zkApp CLI have a major version of 1 or higher,
 changes to the major version of the zkApp CLI will represent
 breaking changes, following semver.
 */
-function hasBreakingChanges(version1, version2) {
-  const version1Arr = version1?.split('.');
-  const version2Arr = version2?.split('.');
+function hasBreakingChanges(installedVersion, latestVersion) {
+  const installedVersionArr = installedVersion?.split('.');
```
Comment (MartinMinkov) [inline src/lib/deploy.js:557]: nit: You could do `installedVersion?.split('.').map(Number)` if you would like to avoid casting twice in the return statements

**Review by MartinMinkov — APPROVED** [review]
LGTM!
