### PR TITLE
Exit the CLI when a project step fails

### LINKED ISSUE #272: Failed NPM install in zk project still gives a success message
moved from https://github.com/o1-labs/snarkyjs/issues/471

```
$ zk project test_snarkyjs_project
✔ Fetch project template
✔ Initialize Git repo
✖ NPM install
✔ Set project name
✔ Git init commit

Success!

Next steps:
  cd test_snarkyjs_project
  git remote add origin <your-repo-url>
  git push -u origin main
```

### PR DESCRIPTION
**Pull request by ymekuria**
Fixes #272 

The CLI now exits when there is a failure in any step during project creation.  We can wait to bump the CLI version until we finish the remaining tasks surrounding the UI scaffold features.

### CODE REVIEW

File: src/lib/project.js [hunk 1]
```diff
@@ -239,6 +239,7 @@ async function step(step, cmd) {
     spin.succeed(green(step));
   } catch (err) {
     spin.fail(step);
+    process.exit();
```
Comment (MartinMinkov) [inline src/lib/project.js:242]: If we omit the error code in `process.exit()`, I believe it returns `0` which is expected to be successful. We should instead do `process.exit(1)` to indicate a failure here in the returned error code.

Comment (jasongitmail) [reply src/lib/project.js]: +1 I just changed it

**Review by jasongitmail — APPROVED** [review]
Looks great. Thanks @ymekuria I'll go ahead and merge it
